angkaPertama = int(input("Angka Pertama : "))
angkaKedua = int(input("Angka Kedua : "))
print("Angka Pertama :", angkaPertama)
print("Angka Kedua :", angkaKedua)
print("Angka Pertama + Angka Kedua :", angkaPertama+angkaKedua)
print("Angka Pertama - Angka Kedua :", angkaPertama-angkaKedua)
print("Angka Pertama x Angka Kedua :", angkaPertama*angkaKedua)
print("Angka Pertama / Angka Kedua :", angkaPertama/angkaKedua)
